[workspace]
authors = ["Locietta <locietta@gmail.com>"]
channels = ["https://prefix.dev/locietta-toolchains", "conda-forge"]
name = "liminal"
platforms = ["win-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.14"
liminal-gcc16-ucrt64 = "==16.1.0"
ninja = "*"
cmake = ">=4.4.0"
clang-format = "==22.1.8"
